### ISSUE TITLE
Question: Which language should I use? Japanese or English

### ISSUE THREAD

**Issue by anatawa12** [yuitosaito/Advanced-Minecraft-Launcher#1]
コミットメッセージなどに日本語度英語どちらを使うべきでしょうか？

**Comment by noyciy7037** [comment]
私は下手な英語使ってますけどどっちがいいんでしょう

**Comment by noyciy7037** [comment]
日本語でお願いします。

**Comment by anatawa12** [comment]
一応僕の場合の話をします。
僕の場合、次の点を判断基準にします。それは「今後海外の人に使ってもらう/開発に参加してもらうつもりがあるか」です。開発に参加してもらうつもりがある場合は英語で書いていたほうがいいと思います

**Comment by noyciy7037** [comment]
海外の方に使ってもらう/開発に参加したもらうことは今のところ考えていないので、(翻訳をしなくていい)日本語が良いと思います。

**Comment by anatawa12** [comment]
わかりました。
